services:
  repo_downloader:
    build: ./microservices/input_integration_pipeline/source/repo_downloader
    ports:
      - "5001:8081"
    networks:
      - microservices-net
    volumes:
      - microservices-data:/app/outputs

  upload_repo_on_blob:
    build: ./microservices/input_integration_pipeline/source/upload_repo_on_blob
    ports:
      - "5002:8082"
    depends_on:
      - repo_downloader
    networks:
      - microservices-net
    volumes:
      - microservices-data:/app/outputs
    env_file:
      - ./microservices/input_integration_pipeline/source/upload_repo_on_blob/.env

  fetch_repo_from_blob:
    build: ./microservices/input_integration_pipeline/source/fetch_repo_from_blob
    ports:
      - "5003:8083"
    depends_on:
      - upload_repo_on_blob
    networks:
      - microservices-net
    volumes:
      - microservices-data:/app/outputs
    env_file:
      - ./microservices/input_integration_pipeline/source/fetch_repo_from_blob/.env

networks:
  microservices-net:
    driver: bridge

volumes:
  microservices-data:
    driver: local