version: '3.8'

services:
  repo_downloader:
    build: ./microservices/repo_downloader
    ports:
      - "5001:8081"
    networks:
      - microservices-net
    volumes:
      - microservices-data:/app/outputs

  upload_repo_on_blob:
    build: ./microservices/upload_repo_on_blob
    ports:
      - "5002:8082"
    depends_on:
      - repo_downloader
    networks:
      - microservices-net
    volumes:
      - microservices-data:/app/outputs
    environment:
      - AZURE_STORAGE_CONNECTION_STRING=${AZURE_STORAGE_CONNECTION_STRING}

  fetch_repo_from_blob:
    build: ./microservices/fetch_repo_from_blob
    ports:
      - "5003:8083"
    depends_on:
      - upload_repo_on_blob
    networks:
      - microservices-net
    volumes:
      - microservices-data:/app/outputs
    environment:
    - AZURE_STORAGE_CONNECTION_STRING=${AZURE_STORAGE_CONNECTION_STRING}

networks:
  microservices-net:
    driver: bridge

volumes:
  microservices-data:
    driver: local